server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/